### ISSUE TITLE
User tests fail for any token other than the one originally used

### ISSUE THREAD

**Issue by M-Zuber** [glosharp/glosharp#11]
I am not quite sure what is a good solution for this..

**Comment by wdhodges** [comment]
Did you copy over the `config-example.json` to `config.json` on the test object? The way I had it set up is that it would check for the `config.json` file and if it didn't find that then it would look for the environment variable `GlosharpToken` but you're right though, probably not the best solution.

**Comment by wdhodges** [comment]
Fixed with refactor. Just make sure you either set up your environment variable or use the config.json file
